### ISSUE TITLE
Import in atom

### ISSUE THREAD

**Issue by martinratinaud** [fsmaia/import-sort-style-module-alias#1]
Hi 

I wanted to test your work but did not find a way to use it locally in atom.

Can you please help me on that ?

Thanks

**Comment by fsmaia** [comment]
I figured out a way to un-hardcode depenencies passing them as options, and just updated README with an example.

I tested (needed to fix also) the integration with VSCode, but I think atom extension should work fine, as they added support in this commit:
https://github.com/renke/import-sort/commit/1c028af0cf5e404a484187e311be09d09c04f3bd

Could you please try again?

Thanks,

**Comment by martinratinaud** [comment]
Thanks and sorry

I did

```
git clone
cd
npm i
npm run build
```

and still I have 

```
error TS5023: Unknown compiler option 'moduleResolution'.
error TS5023: Unknown compiler option 'strictNullChecks'.
```

my `tsc` version is 
```
tsc -v
message TS6029: Version 1.5.3
```

But Anyway, I did what I wanted with another module https://github.com/martinratinaud/organize-imports

Thanks anyway

**Comment by fsmaia** [comment]
Hmm, the project's TypeScript version is `^2.7.2`, as listed in devDependencies. To run tsc directly in CLI you should run `./node_modules/.bin/tsc -v`.

Apparently is happening a misresolution with tsc inside npm script (in my machine I don't have tsc installed globally).

However, to use it in Atom it's enough to set the importSort style to `module-alias`.

May I close this issue or help is still wanted?

Thanks!
