### ISSUE TITLE
Better Documentation?

### ISSUE THREAD

**Issue by ThatSpaceGuy** [fsmaia/import-sort-style-module-alias#2]
I recently installed the VS Code extension sort-imports, and have attempted to use your custom style called import-sort-style-module-alias.

I believe I have followed the (bare-bones) instructions for proper installation (npm i import-sort-style-module-alias), and included the "importSort" property in my package.json file (see below). However, the sort-imports extension does not seem to be recognizing the custom style. (The default styles work fine.) I have restarted VS Code, and rebuilt my project.

What step am I missing to get sort-imports to recognize the custom style I am attempting to use? 

package.json (pared-down):

```
{
  "name": "project-name",
  "version": "0.0.0",
  "scripts": {
    ...
  },
  "private": true,
  "dependencies": {
    ...
  },
  "devDependencies":{
    ...
  },
  "importSort": {
    ".js, .jsx, .es6, .es": {
      "parser": "babylon",
      "style": "module-alias",
      "options": {
        "alias": [
          "@aliasA",
          "@aliasB"
        ]
      }
    },
    ".ts, .tsx": {
      "parser": "typescript",
      "style": "module-alias",
      "options": {
        "alias": [
          "@aliasA",
          "@aliasB"
        ]
      }
    }
  }
}
```
And my tsconfig.json file (pared down):
```
{
  "compileOnSave": false,
  "compilerOptions": {
    ...,
    "paths": {
      "@aliasA/*": ["projects/appA/src/*"],
      "@aliasB/*": ["projects/appB/src/*"]
    }
  }
}
```

**Comment by fsmaia** [comment]
Hmm, your setup looks good. You could run the import-sort CLI to see its output or open the VSCode Output panel on Sort Imports.

Then could you post the output here?

**Comment by ThatSpaceGuy** [comment]
Good idea - there is an error that is showing multiple (for many files):

```
3/24/2020, 11:57:53 AM:
-----------------------
parser.parseImports is not a function
```

What next step should I take? Thanks!

**Comment by fsmaia** [comment]
https://marketplace.visualstudio.com/items?itemName=amatiasq.sort-imports
Take a look at Troubleshooting, think we found the problem :)

**Comment by fsmaia** [comment]
This error happens in extension's integration with TypeScript, IMHO it would be redundant to have this alert here too.
